
services:
  x3_ai_toolchain:
    image: openexplorer/ai_toolchain_ubuntu_20_xj3_cpu:v2.6.4
    stdin_open: true
    tty: true
    volumes:
    # change the paths according to OE version
    # e.g. ./open_explorer/horizon_xj3_open_explorer_{your_version}:/open_explorer}
      - ./open_explorer/horizon_xj3_open_explorer_v2.6.6-py38_20240717:/open_explorer
    # change the dataset path accordingly
      - ./dataset:/data/horizon_xj3/data
  
    # To run interactively and remove container after exit, use:
    # docker compose run --rm ai_toolchain
